# version: '3.8'
# services:
#   app:
#     build:
#       context: .
#     container_name: express-app-server
#     ports:
#       - '3000:3000'
#     environment:
#       - NODE_ENV=development
#       - MONGO_URL=mongodb://mongo:27017/mydatabase
#       - REDIS_URL=redis://redis:6379
#     depends_on:
#       - mongo
#       - redis
#   mongo:
#     image: mongo
#     container_name: mongo-db
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: mongo
#       MONGO_INITDB_ROOT_PASSWORD: Abcd_1234
#       MONGO_INITDB_DATABASE: mydatabase
#     volumes:
#       - mongo_data:/data/db
#     ports:
#       - '27017:27017'
#   redis:
#     image: redis:alpine
#     container_name: redis-mongo
#     ports:
#       - '6379:6379'
#     volumes:
#       - redis_data:/data
#   mongo-express:
#     image: mongo-express
#     container_name: mongo-express
#     environment:
#       ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
#       ME_CONFIG_MONGODB_ADMINPASSWORD: Abcd_1234
#       ME_CONFIG_MONGODB_SERVER: mongo
#     ports:
#       - '8081:8081'
#     depends_on:
#       - mongo
# volumes:
#   mongo_data:
#   redis_data:





version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@db:5432/mydatabase
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  redis:
    image: redis:alpine
    container_name: redis-cache
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '8080:80'
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
volumes:
  postgres_data:
  redis_data:
  pgadmin_data: