version: '3.9'

services:
  mongo:
    image: mongo:latest
    container_name: local_mongo
    restart: always
    ports:
      - "27017:27017"

  mongoexpress:
    image: mongo-express
    container_name: mongo_container
    ports:
      - "8081:8081"
    environment: 
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017
      - ME_CONFIG_BASICAUTH=true
    depends_on:
      - mongo
    restart: always

  redis:
    image: redis:latest
    container_name: my_custom_redis_mongo
    restart: always
    ports:
      - "6379:6379"


volumes:
  mongo_data:
    driver: local
 